parser: 'vue-eslint-parser'

parserOptions:
  parser: "@typescript-eslint/parser"

extends:
  - 'eslint:recommended'
  - 'plugin:vue/vue3-recommended'
  - 'plugin:@typescript-eslint/recommended'

rules:
  vue/html-self-closing: off
  vue/max-attributes-per-line: off
  vue/multi-word-component-names: off
  vue/no-v-html: off
